version: '3.5'

services:
  contracts-env:
    user: "${USERID?}:${USERID?}"
    env_file:
      - .env
    build:
      context: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/src:rw
      - $HOME/.tenderly/config.yaml:/root/.tenderly/config.yaml:ro
    #environment:
      #- MNEMONIC=
      #- RPC_URL=
      #- BLOCK_EXPLORER_KEY=
      #- TENDERLY_PROJECT=
      #- TENDERLY_USERNAME=
      #- TENDERLY_FORK_ID=
      #- TENDERLY_HEAD_ID=
