version: '3.5'

services:
  contracts-env:
    security_opt:
      - no-new-privileges
    user: 1001:1001
    env_file:
      - .env
    build:
      context: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/src:rw
      - $HOME/.tenderly/config.yaml:/root/.tenderly/config.yaml:ro
    #environment:
      #- MNEMONIC=
      #- ETHERSCAN_KEY=
      #- INFURA_KEY=
      #- ETHERSCAN_NETWORK=
      #- TENDERLY_PROJECT=
      #- TENDERLY_USERNAME=
      #- ALCHEMY_KEY=
      #- TENDERLY_FORK_ID=
      #- TENDERLY_HEAD_ID=
